env: 
  game: geometric-local_maze #Pendulum-v0
  num_train_episodes: 25 #45
  max_episode_length: 30
  num_train_epochs: 10 #1
  n_rollouts_per_step: 20
  n_trials_for_search_time: 10
  max_size: 10
  lo: -10
  hi: 10