defaults:
  - agent: DiscreteAgent
  - mcts: MCTSDiscrete
  - optimizer: RMSProp
  - policy: DiscretePolicy
  - loss: A0CLossTuned

game: CartPole-v0
seed: 34
num_train_episodes: 200
max_episode_length: 200
num_train_epochs: 5
device: cpu

buffer:
  _target_: alphazero.agent.buffers.ReplayBuffer
  # max_size: 1000
  # batch_size: 32
  max_size: 3000
  batch_size: 256
