defaults:
  - agent: OneShotAgent2
  - mcts: MCTSOpenLoopContinuous
  - optimizer: RMSProp
  # - optimizer: Adam
  - policy: DensityPolicy #ContinuousPolicy #
  - loss: OneShotLoss
  - env: Quadcopter
  - her: her
    

# game: PointMaze_Open-v3 #FetchReach-v3
game: FetchReach-v3 #Pendulum-v0
# game: FetchPush-v2
# game: HalfCheetah-v4 #Pendulum-v0
# game: HumanoidStandup-v4
seed: 34
num_train_episodes: 10
max_episode_length: 50 #0
num_train_epochs: 30
device: cpu


train_her: True
train_az: False
standard_her: True

trainer: 
  _target_: open_loop_trainer.OpenLoopTrainer

buffer:
  # _target_: alphazero.agent.buffers.ReplayBuffer
  _target_: alphazero.agent.buffers.NonConstantActionReplayBuffer
  # max_size: 3000
  # batch_size: 256
  # max_size: 30000
  # batch_size: 1000
  max_size: 5000
  batch_size: 256
  # max_size: 10000
  # batch_size: 100
