defaults:
  - agent: NGUAgent
  - mcts: MCTSNGU
  - optimizer: RMSProp
  - policy: DensityPolicy
  - loss: A0CLossTuned
    

game: HalfCheetah-v4 #Pendulum-v0
# game: Humanoid-v4 #Pendulum-v0
# game: Pendulum-v1
seed: 34
num_train_episodes: 45
max_episode_length: 200
num_train_epochs: 10
device: cpu

buffer:
  _target_: alphazero.agent.buffers.ReplayBuffer
  max_size: 3000
  batch_size: 32
