defaults:
  - agent: ExternalTrainingHERAgent
  - mcts: MCTS_HER
  - optimizer: RMSProp
  # - optimizer: Adam
  - policy: HERDensityPolicy #ContinuousPolicy #
  # - policy: HERDensityPolicy
  # - loss: HERLoss
  - loss: OneShotLoss
  - env: Quadcopter
  - her: her
    

    

game: ??? #FetchReach-v3 #Pendulum-v0
# game: FetchPush-v2
# game: PointMaze_Open-v3 #FetchReach-v3
# game: Humanoid-v4 #Pendulum-v0
# game: Pendulum-v1
seed: 34
num_train_episodes: ??? #10 #45
max_episode_length: ??? #50
num_train_epochs: ??? #10 #1
device: cpu

train_her: True
# train_az: True
train_az: False
standard_her: True

name: SST

trainer: 
  _target_: sst_trainer.SSTTrainer

buffer:
  # _target_: alphazero.agent.buffers.ReplayBuffer
  _target_: alphazero.agent.buffers.NonConstantActionReplayBuffer
  # max_size: 3000
  # batch_size: 256
  # max_size: 30000
  # batch_size: 1000
  max_size: 5000
  batch_size: 256
  # max_size: 10000
  # batch_size: 100
